// <auto-generated />
using System;
using CalculadoraImposto.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculadoraImposto.API.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalculadoraImposto.API.Core.Entities.Empresa", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailResponsavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.HasIndex("RazaoSocial")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("CalculadoraImposto.API.Core.Entities.Imposto", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Aliquota")
                        .HasColumnType("float");

                    b.Property<int>("AnoReferencia")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmpresaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ImpostoEmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LucroPresumido")
                        .HasColumnType("float");

                    b.Property<int>("MesReferencia")
                        .HasColumnType("int");

                    b.Property<double>("ValorImposto")
                        .HasColumnType("float");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("EmpresaID");

                    b.HasIndex("ImpostoEmpresaId");

                    b.ToTable("Impostos");
                });

            modelBuilder.Entity("CalculadoraImposto.API.Core.Entities.NotaFiscal", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmpresaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NotaFiscalEmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Serie")
                        .HasColumnType("int");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("EmpresaID");

                    b.HasIndex("NotaFiscalEmpresaId");

                    b.ToTable("NotasFiscais");
                });

            modelBuilder.Entity("CalculadoraImposto.API.Core.Entities.Imposto", b =>
                {
                    b.HasOne("CalculadoraImposto.API.Core.Entities.Empresa", "Empresa")
                        .WithMany("Impostos")
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalculadoraImposto.API.Core.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("ImpostoEmpresaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("CalculadoraImposto.API.Core.Entities.NotaFiscal", b =>
                {
                    b.HasOne("CalculadoraImposto.API.Core.Entities.Empresa", null)
                        .WithMany("NotasFiscais")
                        .HasForeignKey("EmpresaID");

                    b.HasOne("CalculadoraImposto.API.Core.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("NotaFiscalEmpresaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("CalculadoraImposto.API.Core.Entities.Empresa", b =>
                {
                    b.Navigation("Impostos");

                    b.Navigation("NotasFiscais");
                });
#pragma warning restore 612, 618
        }
    }
}
